### ISSUE TITLE
If statement opening braces on new line

### ISSUE THREAD

**Issue by modelesque** [gerardroche/sublime-php-snippets#6]
Typing `if` creates:

	if (expr) {
		
	}

But I would like it to be:

	if (expr) 
	{
		
	}

Same for `else` statements.  

	if (expr) 
	{
		
	}
	else
	{
		
	}

It works (as default) for `f` (function).  Would prefer all braces on new lines for my oop work.

**Comment by gerardroche** [comment]
Configure your preferences with this:

```

			<dict>
				<key>name</key>
				<string>TM_PHP_SNIPPET_OPENING_BRACE</string>
				<key>value</key>
				<string>
{</string>
			</dict>
```

See https://github.com/gerardroche/sublime-php-snippets#configuration.

That variable dertimines how *all* opening braces are formatted. In the above config it means a newline, then the brace. The default is PSR compliant.
