### ISSUE TITLE
<?<?php  ?>

### ISSUE THREAD

**Issue by Skatilsya** [gerardroche/sublime-php-snippets#8]
Hey. When I try to get `<? php?>` from `<?` I get `<? <? php?>`.
What am I doing wrong?

**Comment by gerardroche** [comment]
What type of file and syntax are you trying the snippet from e.g. `*.html`, `*.php`, `*.phtml`?

In a `*.php` file there should three related snippets: `<?`, `<?=`, and `?=`.

`<?` should complete as 

```
<?php

|
```

Try enabling debug logging to see if something else is overriding the snippet:

Show the Sublime Text console log: Menu > View > Show Console.

Command and input logging are enabled by running the following commands in input box at the bottom of the console:

```
sublime.log_commands(True); sublime.log_input(True)
```

**Comment by Skatilsya** [comment]
Oh yes. This works fine in `*.php` files but I have issue with `*.html`
This plugin does not work with html?

![изображение](https://user-images.githubusercontent.com/57448475/86519500-02aa7300-be44-11ea-8c0c-ff51a2630874.png)

**Comment by gerardroche** [comment]
I've added a `<?` snippet.

You can also use the "php" snippet which is a little easier i.e. type "php" then your autocomplete key (`<Ctrl+Space>` or `<Tab`> if you use tab to auto complete).

## Tip

There is also an "echo" snippet in HTML that will complete as `<?= |$var| ?>`. 

If you prefer the long-form echo statements i.e. `<?php echo |$var| ?>`, you can configure it. Essentially, just create a configuration file (see https://github.com/gerardroche/sublime-php-snippets#configuration), and comment or delete the following section:  

```
<dict>
    <key>name</key>
    <string>TM_PHP_OPEN_TAG_WITH_ECHO</string>
    <key>value</key>
    <string>=</string>
</dict>
```
